### ISSUE TITLE
Use JMM Watched Status % 

### ISSUE THREAD

**Issue by ElementalCrisis** [bigretromike/nakamoriplugin#41]
Currently you have it set to 80% for watched status, would it be possible to have Nakamori pull the data from JMM as you are able to set a watched status % in there? If not can you make this a user input field?

**Comment by bigretromike** [comment]
Are you wanting to sync how much you watched current video, to be able to continue watching somewhere else? That ain't related with being marked as watched.

I will add ability to setup the %, I use it because I like to skip Ending so I more like never can hit 100% of episode to make it auto marked as watched.

**Comment by bigretromike** [comment]
Please check 1.1.9 from develop and please tell if the first part of your question/request is this: https://github.com/bigretromike/nakamoriplugin/issues/20

**Comment by ElementalCrisis** [comment]
We can set the watched % in JMM Desktop, can you make it an option to have it import the watched % from JMM Desktop?

**Comment by bigretromike** [comment]
I think its possible - I will look on the code if JMMServer throw out that info, if not I will add it to Service if Yes, the new version is behind the corner ;-)

**Comment by bigretromike** [comment]
Now I know what you askd for and yes, this was added in 1.1.9
