### ISSUE TITLE
Suggestion: Option For Random Poster For Series

### ISSUE THREAD

**Issue by ElementalCrisis** [bigretromike/nakamoriplugin#47]
I've noticed that while the background images change, the series poster never does. I'd like to suggest the option to allow random posters for series.

**Comment by bigretromike** [comment]
This is JMM Service side. But that could be also done. But that could make some missunderstanding because everytime you would load main view the images would change also and you could think that you dont remamber this series because it use new image? But i will look into it so it could be optional ;-) on both ends

**Comment by ElementalCrisis** [comment]
Oh, if its JMM side than don't worry about it. The feature was removed because it was causing speed issues.

**Comment by bigretromike** [comment]
I can introduce it to Kodi Service implementation with maybe some tweaks ;-) If I will have time I will try - that would be on/off in settings for Nakamori so no effect on JMMClient

**Comment by bigretromike** [comment]
from perspective of viewing few series, I more likely find series I want via Image than name. Changing images would confuse IMO. 

If there will be more need for this It can be done.
