### ISSUE TITLE
Kodi 16.1 RC2 - Subgroups don't have info for individual series

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamoriplugin#75]
When a show is in a group (the setting in JMM to group related shows), the top most level of the group has info, but when opening the group to reveal the shows, they all say "No Information".

**Comment by da3dsoul** [comment]
This one happens with JMM 3.4.6.4

**Comment by da3dsoul** [comment]
![Root](https://dl.dropboxusercontent.com/u/31454410/Github%20Issues/screenshot000.png)
![Subgroup1](https://dl.dropboxusercontent.com/u/31454410/Github%20Issues/screenshot001.png)
![Sbugroup2](https://dl.dropboxusercontent.com/u/31454410/Github%20Issues/screenshot002.png)
Because I'm better with pictures than words. Sorry, I run in 4K.

**Comment by bigretromike** [comment]
You did well with those screen shots.
May I ask you what Skin is that because you should also try it with default skin because alot of 'info related' bugs usly are related to skins, and giving skin name would help me add support to it if this is skin related issue ;-)
Also Im not sure If I ever used this function in JMM ;-) So another thing I could left undone :-)

**Comment by da3dsoul** [comment]
KOver, I've modified the picture preview settings on it a bit, so the lack of fan art is probably my fault, but I'll try on the default

**Comment by bigretromike** [comment]
KOver from what is see is not common skin :-) and looks very interesting - thanks for the info I will try to find time and look into it because I could make it to work because it looks very clean and slick ;-)

**Comment by da3dsoul** [comment]
Yes, I love the skin. The others are less intuitive with a gamepad in my opinion, and a dark theme is a must....

**Comment by da3dsoul** [comment]
I tried (disdain) Confluence...it doesn't work there either, though.

**Comment by da3dsoul** [comment]
I figured out the cause for this; unfortunately, the fix is not so easy. Nakamori operates on the assumption that the only possible trees are main->Filters->TV shows->seasons->episodes and main->Filters->TV shows->episodes, if there is only one season with no credits or specials. JMM supports as many subgroups as you want, so we need to detect the type of items in a directory

**Comment by bigretromike** [comment]
Nakamori used to use that scheme. Now its more like Filter > Shows > infinity seasons > episodes

**Comment by bigretromike** [comment]
When grouping: JMM use first anime in Group as 'default' one to serve info.
Also there is a problem that JMM server all Series/Group as "Show". 
This is probably resole of adding more and more support without refactoring objects that are used to serve items.
But I did hack it a bit - because you are so helpful so i fixed something you wanted to be fixed ;-)
