### ISSUE TITLE
Kodi crashing a lot

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamoriplugin#89]
This isn't so much a bug report as an inquiry. Have you had issues with Kodi crashing while playing things from the Continue Watching menu? I can't reliably reproduce it. All I know is it only happens when backing out of a finished episode. When started back up, the episode is not marked as Watched.

**Comment by da3dsoul** [comment]
NVM after extensive searching, dxva doesn't play nice with some encodings. Nothing to do with Nakamori or JMM. If you ever have the issue, try setting the render method to software or automatic, and disable DXVA2

**Comment by bigretromike** [comment]
^_^ good news that is not nakamori/jmm problem. There been a playing issue on android but that was for all files :-)

**Comment by da3dsoul** [comment]
Android is difficult because the hardware is so varied. You're best off setting the render to software and saving yourself a headache, as everything is HEVC or Hi10p at this point, which nothing can hardware decode.

**Comment by bigretromike** [comment]
hehehe true true

**Comment by da3dsoul** [comment]
It'd be nice if they would make an htpc aimed video card that focuses on decoding acceleration and leaving out the fancy 3d stuff. They could justify the cost of developing HEVC and Hi10p hardware decoding chips and sell them to TV and DVR manufacturers. Plus the ability to skimp out on expensive Intel CPUs in favor of a video processor designed to be in media players would be so nice. A 4790K should not be needed to play 1080p video with subtitles...

**Comment by da3dsoul** [comment]
Of course, I've been proposing this idea since 2011 when Hi10p was getting popular... So it's clearly not gonna happen

**Comment by bigretromike** [comment]
HMM i think that this is semi-how you wanted but in diffrent way. Alot of RPi's clones have hardware decoders but the 'official standard' is h.264 until this changes there probably will be dedicated boards.
To be honest it wouldn't matter much, because alot good quality anime release are with so big bitrate and profiles the even with hardware decoding this could be chanlenging for embed solution. And using PC with low end CPU able to decode this is ok. Also the CUDA/OpenCL is useful to but I allways end up with broken video play when using those technology with combination of ultra-quality releases ;-)
Yea, probably im bumbling a bit - that because its one of those days

**Comment by da3dsoul** [comment]
They can decode 8-bit h.264. Hi10p (aka 10-bit h.264) is supposedly too complicated an algorithm to hardware decode in a reasonable chip space. Hopefully, we'll get HEVC decoding in the next couple years, but everyone is so used to software decoding and hardware scaling that manufacturers don't want to spend money on research and development.

**Comment by da3dsoul** [comment]
And yeah, it's 6am here. I really don't have anything better to do at work

**Comment by bigretromike** [comment]
I think for now it would be cheaper to upgrade CPU for software decoding than buy dedicated card to decode HEVC. Until the cheap CPU will choke with decoding until then we see dedicated hevc cards :-) which would be cool
